version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: "Testing"
          shell: /bin/sh
          command: |
                 mkdir ~/testing
                 echo pwd
          
      
          
