version: 2
jobs:
  build:
    docker:
      - image: ubuntu

    environment:
      TEST_REPORTS: /tmp/test-reports

    working_directory: ~/my-project

    steps:
      - checkout

      - run:
         # command: echo "Hello World" | docker run ubuntu

  deploy-stage:
    docker:
      - image: ubuntu
    working_directory: /tmp/my-project
    steps:
      - run:

