version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu
      - image: hashicorp/terraform:light
    steps:
      - checkouts
      - run:
        name: terraform init
        command: |
          source $BASH_ENV
          cd environments/$TERRAFORM_ENVIRONMENT
          terraform init
          

          
          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  