version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:14.04
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: "Testing"
          shell: /bin/sh
          command: |
                 mkdir ~/testing
                 echo pwd
          
      
          
