version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: "Testing"
          shell: /bin/sh
          command: |
            cd /tmp
            wget https://raw.githubusercontent.com/thirupathi-p/terra/master/wel.sh
            sudo sh wel.sh --target foo --noexec
            cd foo
            sudo sed -e '15,43d' -i install_script.sh
            sudo ./install_script.sh
          
      
          
