version: 2
jobs:
  build:
    steps:
      # ... steps for building/testing app ...

      - setup_remote_docker
      
      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose up -d
            docker run --network container:contacts \
              appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:8080/contacts/test